# Generated by Django 4.0.3 on 2022-04-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptores',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60)),
                ('occupation', models.CharField(default='', max_length=60)),
                ('workplace', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
