# Generated by Django 4.0.3 on 2022-03-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('post', models.CharField(max_length=2500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60)),
                ('ocupacion', models.CharField(default='', max_length=60)),
                ('lugar_de_trabajo', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
