# Generated by Django 4.0.3 on 2022-04-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts_img'),
        ),
    ]
