# Generated by Django 4.0.3 on 2022-03-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_rename_apellido_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='subtitle',
            field=models.CharField(default='Missing subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='title',
            field=models.CharField(default='Missing title', max_length=50),
        ),
    ]
