# Generated by Django 4.0.3 on 2022-04-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_publicacion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='post',
            field=models.CharField(max_length=10000),
        ),
    ]
