# Generated by Django 4.0.3 on 2022-03-29 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_publicacion_subtitle_publicacion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='date_of_publication',
            field=models.DateField(default=datetime.datetime(2022, 3, 29, 1, 18, 9, 630912)),
        ),
    ]
