# Generated by Django 4.0.3 on 2022-03-29 04:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_publicacion_date_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='date_of_publication',
            field=models.DateField(default=datetime.datetime(2022, 3, 29, 4, 20, 53, 136043, tzinfo=utc)),
        ),
    ]
