# Generated by Django 4.0.3 on 2022-04-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_alter_publicacion_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='author',
            field=models.CharField(default='Missing author', max_length=150),
        ),
    ]
