# Generated by Django 4.0.3 on 2022-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_alter_publicacion_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='subtitle',
            field=models.CharField(default='Missing subtitle', max_length=150),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='title',
            field=models.CharField(default='Missing title', max_length=100),
        ),
    ]
