# Generated by Django 4.0.3 on 2022-03-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_publicacion_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='date_of_publication',
        ),
    ]
