# Generated by Django 4.0.3 on 2022-03-29 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_remove_publicacion_date_of_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='date_of_publication',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
