# Generated by Django 4.0.3 on 2022-03-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0010_publicacion_date_of_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptores',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
    ]
