# Generated by Django 4.0.3 on 2022-04-26 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sender', models.CharField(default='Missing author', max_length=40)),
                ('receiver', models.CharField(default='Missing author', max_length=40)),
                ('message', models.CharField(max_length=15000)),
            ],
        ),
    ]
