# Generated by Django 4.0.3 on 2022-04-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_publicacion_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='post',
            field=models.CharField(max_length=15000),
        ),
    ]
